### ISSUE TITLE
ECMA262 target URL ( ECMAScript version and Regular Expressions)

### ISSUE THREAD

**Issue by BurtHarris** [cbor-wg/CBORbis#22]
The YAML data in **draft-ietf-cbor-7049.md** includes this normative reference.

```
normative:
  ECMA262:
    target: http://www.ecma-international.org/publications/files/ecma-st/ECMA-262.pdf
    title: ECMAScript Language Specification 5.1 Edition
    author:
    - org: European Computer Manufacturers Association
    date: 2011-06
    seriesinfo:
      ECMA: Standard ECMA-262
```

Minor issue:  While the title specifies **ECMAScript 5.1**, the URL currently points to the **ECMAScript® 2017 Language Specification**.    

If we really want to make ECMAScript 5.1 normative, the URL should probably read https://www.ecma-international.org/ecma-262/5.1/   However, I believe there might be substantial value in the CBORbis in updating the normative reference to the most recent version.   I would also suggest linking to the version-specific browsable HTML URL:  https://www.ecma-international.org/ecma-262/8.0/
